// fe-apps/todo-angular/src/app/pages/signup/signup.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from 'src/app/services/auth.service';

@Component({
  selector: 'app-signup',
  templateUrl: './signup.component.html',
  styleUrls: ['./signup.component.scss']
})
export class SignupComponent implements OnInit {
  signupObj = {
    email: '',
    name: '',
    password: '',
    rePassword: '',
    isAdmin: false,
    errorMsg: '',
    successMsg: ''
  };

  constructor(private authSrvc: AuthService) { }

  ngOnInit() { }

  signUp() {
    if (this.signupObj.password === this.signupObj.rePassword) {
      this.signupObj.successMsg = '';
      this.signupObj.errorMsg = '';
      const registerObj = {
        email: this.signupObj.email,
        name: this.signupObj.name,
        password: this.signupObj.password,
        isAdmin: this.signupObj.isAdmin,
      };
      this.authSrvc.signUp(registerObj).subscribe(
        signed => {
          this.resetSignupForm();
          this.signupObj.successMsg = signed.message;
        },
        error => {
          this.signupObj.errorMsg = error.error.message;
        }
      );
    } else {
      this.signupObj.errorMsg = 'Please enter matching passwords';
    }
  }

  resetSignupForm() {
    Object.keys(this.signupObj).forEach(key => {
      this.signupObj[key] = '';
    });
  }
}

<div class="row container form-card">
  <div class="col s12">
    <div class="card">
      <form #signupForm="ngForm" (ngSubmit)="signUp()">
        <div class="card-content">
          <div class="card-title">Sign Up</div>
          <div class="input-field">
            <label for="name" class="active">Name</label>
            <input id="name" name="name" [(ngModel)]="signupObj.name" placeholder="Name" type="text" required>
          </div>
          <div class="input-field">
            <label for="email" class="active">Email</label>
            <input id="email" name="email" [(ngModel)]="signupObj.email" placeholder="Email" type="text" required>
          </div>
          <div class="input-field">
            <label for="password" class="active">Password</label>
            <input id="password" name="password" [(ngModel)]="signupObj.password" placeholder="Password" type="password" required>
          </div>
          <div class="input-field">
            <label for="rePassword" class="active">Re-Enter Password</label>
            <input id="rePassword" name="rePassword" [(ngModel)]="signupObj.rePassword" placeholder="Re-Enter Password" type="password" required>
          </div>
          <div class="row">
            <div class="col s6">Is an admin user</div>
            <div class="switch col s6">
              <label>
                No
                <input type="checkbox" name="isAdmin" [(ngModel)]="signupObj.isAdmin" [checked]="signupObj.isAdmin">
                <span class="lever"></span>
                Yes
              </label>
            </div>
          </div>
          <div class="error red-text" *ngIf="signupObj.errorMsg">{{signupObj.errorMsg}}</div>
          <div class="success green-text" *ngIf="signupObj.successMsg">{{signupObj.successMsg}}. <a routerLink="/login">Log In</a></div>
        </div>
        <div class="card-action">
          <button type="submit" class="waves-effect waves-light btn" [disabled]="!signupForm.form.valid">Sign Up</button>
        </div>
      </form>
    </div>
    <p>Already have an account? <a routerLink="/login">Log In</a></p>
  </div>
</div>

// fe-apps/todo-vue/src/pages/signup/Signup.vue
<template src="./signup.html"></template>

<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import { Validations } from 'vuelidate-property-decorators';
import { required } from 'vuelidate/lib/validators';
import authSrvc from '../../services/auth-service';

@Component({})
export default class Signup extends Vue {
  private signupObj = {
    email: '',
    name: '',
    password: '',
    rePassword: '',
    isAdmin: false,
    errorMsg: '',
    successMsg: ''
  };

  @Validations()
  validations = {
    email: { required },
    name: { required },
    password: { required },
    rePassword: { required }
  };

  private get disabledSignup(): boolean {
    const disabled = this.signupObj.email && this.signupObj.name && this.signupObj.password && this.signupObj.rePassword ? false : true; 
    return disabled;
  }

  private signUp() {
    const self = this;
    if (this.signupObj.password === this.signupObj.rePassword) {
      this.signupObj.successMsg = '';
      this.signupObj.errorMsg = '';
      const registerObj = {
        email: this.signupObj.email,
        name: this.signupObj.name,
        password: this.signupObj.password,
        isAdmin: this.signupObj.isAdmin,
      };
      authSrvc.signUp(registerObj).then(signed => {
        signed = signed.data
        self.resetSignupForm();
        self.signupObj.successMsg = signed.message;
      }).catch(error => {
        error = error.response.data;
        self.signupObj.errorMsg = error.message;
      });
    }
  }

  private resetSignupForm() {
    const self = this;
    Object.keys(this.signupObj).forEach(key => {
      self.signupObj[key] = '';
    });
  }
}
</script>

<style lang="scss">
</style>
